# Auto-generated by fqa unpack. Cross-platform pack script.
import subprocess
import sys
from pathlib import Path

def main():
    root = Path(__file__).resolve().parent
    cfg = root / ".fqa-tool-path"
    if not cfg.exists():
        print("ERROR: .fqa-tool-path not found. Run 'fqa unpack' or create it.", file=sys.stderr)
        sys.exit(1)
    line = cfg.read_text(encoding="utf-8").strip().splitlines()
    line = [l.strip() for l in line if l.strip()]
    if not line:
        print("ERROR: .fqa-tool-path is empty.", file=sys.stderr)
        sys.exit(1)
    # First non-empty line = full command (e.g. "python /path/to/fqa.py" or "/path/to/fqa.exe")
    cmd_str = line[0]
    # Parse respecting quoted parts so paths with spaces work
    import shlex
    parts = shlex.split(cmd_str)
    args = parts + ["pack", "."] + [a for a in sys.argv[1:]]
    subprocess.check_call(args, cwd=root)

if __name__ == "__main__":
    main()
